workflows:
  flutter-workflow:
    name: Flutter CI/CD Workflow
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - firebase_credentials
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Run Flutter tests
        script: flutter test

      - name: Build Android APK
        script: flutter build apk --release

      - name: Build iOS (No Code Sign)
        script: |
          flutter build ios --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     build

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/*.ipa

    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: $FIREBASE_APP_ID
        ios:
          app_id: $FIREBASE_IOS_APP_ID

